baseURL = "https://nukosuke.github.io/hugo-librarian-demo/"
languageCode = "en-us"
title = "Librarian"
theme = "librarian"
googleAnalytics = "UA-123-45"
disqusShortname = "hugo-librarian-demo"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[module]
  [[module.mounts]]
    source = "assets/stylesheets"
    target = "assets/stylesheets"
  [[module.mounts]]
    source = "node_modules/bulma"
    target = "assets/stylesheets/bulma"

[Params]
  author = "nukosuke"
  subtitle = "Hugo theme"
